// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-collections.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-collections.ts
var list_collections_default = defineTool({
  name: "list_collections",
  title: "List collections",
  description: "List the signed-in user's collections (watches, sneakers, purses).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("collections").select("id, name, collection_type, created_at").order("created_at");
    if (error) throw new ToolError(error.message);
    const collections = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      collection_type: c.collection_type
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(collections) }],
      structuredContent: { collections }
    };
  }
});

// src/lib/mcp/tools/list-items.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";
var list_items_default = defineTool2({
  name: "list_items",
  title: "List collection items",
  description: "List items (watches, sneakers, purses) the signed-in user owns, optionally filtered by collection or status.",
  inputSchema: {
    collection_id: z.string().uuid().optional().describe("Only items in this collection."),
    status: z.enum(["active", "sold", "traded"]).optional().describe("Filter by item status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ collection_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const sb = supabaseForUser(ctx);
    let q = sb.from("watches").select("id, brand, model, reference, year, dial_color, type, cost, msrp, average_resale_price, status, collection_id").eq("user_id", ctx.getUserId()).order("sort_order");
    if (collection_id) q = q.eq("collection_id", collection_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) throw new ToolError2(error.message);
    const items = (data ?? []).map((w) => ({
      id: w.id,
      brand: w.brand,
      model: w.model,
      reference: w.reference ?? null,
      year: w.year ?? null,
      dial_color: w.dial_color,
      type: w.type,
      price_paid: Number(w.cost),
      msrp: w.msrp == null ? null : Number(w.msrp),
      market_value: w.average_resale_price == null ? null : Number(w.average_resale_price),
      status: w.status,
      collection_id: w.collection_id ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/list-wears.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var list_wears_default = defineTool3({
  name: "list_wears",
  title: "List recent wears",
  description: "List the signed-in user's recent wear log entries, newest first.",
  inputSchema: {
    days_back: z2.number().int().min(1).max(365).default(30).describe("How many days back to include.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_back }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const sb = supabaseForUser(ctx);
    const since = new Date(Date.now() - days_back * 864e5).toISOString().slice(0, 10);
    const { data, error } = await sb.from("wear_entries").select("id, wear_date, days, notes, watch_id, watches(brand, model)").eq("user_id", ctx.getUserId()).gte("wear_date", since).order("wear_date", { ascending: false });
    if (error) throw new ToolError3(error.message);
    const wears = (data ?? []).map((e) => ({
      id: e.id,
      date: e.wear_date,
      days: Number(e.days),
      notes: e.notes ?? null,
      item_id: e.watch_id,
      item: e.watches ? `${e.watches.brand} ${e.watches.model}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(wears) }],
      structuredContent: { wears }
    };
  }
});

// src/lib/mcp/tools/log-wear.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var log_wear_default = defineTool4({
  name: "log_wear",
  title: "Log a wear",
  description: "Record that the signed-in user wore/carried one of their items on a date.",
  inputSchema: {
    item_id: z3.string().uuid().describe("ID of the item (from list_items)."),
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Date in YYYY-MM-DD."),
    days: z3.union([z3.literal(0.25), z3.literal(0.5), z3.literal(1)]).default(1).describe("Portion of the day: 0.25, 0.5 or 1."),
    notes: z3.string().max(500).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ item_id, date, days, notes }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing, error: exErr } = await sb.from("wear_entries").select("days").eq("user_id", userId).eq("wear_date", date);
    if (exErr) throw new ToolError4(exErr.message);
    const used = (existing ?? []).reduce((s, r) => s + Number(r.days), 0);
    if (used + days > 1) throw new ToolError4(`Only ${Math.max(0, 1 - used)} day remaining on ${date}.`);
    const { data, error } = await sb.from("wear_entries").insert({ user_id: userId, watch_id: item_id, wear_date: date, days, notes: notes ?? null }).select("id").single();
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: `Logged wear ${data.id} on ${date}.` }],
      structuredContent: { id: data.id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "thrwpxiahqgubjkjnkgt";
var mcp_default = defineMcp({
  name: "sora-vault",
  title: "Sora Vault",
  version: "0.1.0",
  instructions: "Tools for Sora Vault, a collection tracker for watches, sneakers and purses. Use list_collections and list_items to see what the user owns, list_wears for recent wear history, and log_wear to record a wear.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_collections_default, list_items_default, list_wears_default, log_wear_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
